raw_output = "false"
user_token = ""

[filter]
  limit = "10"
  offset = "0"
  topic = ""

[remotes]
  certs_url = "http://localhost:9019"
  channels_url = "http://localhost:9005"
  clients_url = "http://localhost:9006"
  domains_url = "http://localhost:9003"
  groups_url = "http://localhost:9004"
  host_url = "http://localhost"
  http_adapter_url = "http://localhost:8008"
  journal_url = "http://localhost:9021"
  tls_verification = false
  users_url = "http://localhost:9002"