global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mitras'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    follow_redirects: true
    static_configs:
    - targets: 
      - mitras-clients:9000
      - mitras-users:9002
      - mitras-http:8008
      - mitras-ws:8186
      - mitras-coap:5683
