# This docker-compose file contains optional Prometheus and Grafana service for Mitras platform.
# Since this service is optional, this file is dependent of docker-compose.yaml file
# from <project_root>/docker. In order to run this service, execute command:
# docker compose -f docker/addons/prometheus/docker-compose.yaml up
# from project root.

networks:
  mitras-base-net:

volumes:
  mitras-prometheus-volume:

services:
  promethues:
    image: prom/prometheus:v2.49.1
    container_name: mitras-prometheus
    restart: on-failure
    ports:
      - ${MITRAS_PROMETHEUS_PORT}:${MITRAS_PROMETHEUS_PORT}
    networks:
      - mitras-base-net
    volumes:
      - type: bind
        source: ./metrics/prometheus.yaml
        target: /etc/prometheus/prometheus.yaml
      - mitras-prometheus-volume:/prometheus

  grafana:
    image: grafana/grafana:10.2.3
    container_name: mitras-grafana
    depends_on:
      - promethues
    restart: on-failure
    ports:
      - ${MITRAS_GRAFANA_PORT}:${MITRAS_GRAFANA_PORT}
    environment:
      - GF_SECURITY_ADMIN_USER=${MITRAS_GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${MITRAS_GRAFANA_ADMIN_PASSWORD}
    networks:
      - mitras-base-net
    volumes:
      - type: bind
        source: ./grafana/datasource.yaml
        target: /etc/grafana/provisioning/datasources/datasource.yaml
      - type: bind
        source: ./grafana/dashboard.yaml
        target: /etc/grafana/provisioning/dashboards/main.yaml
      - type: bind
        source: ./grafana/example-dashboard.json
        target: /var/lib/grafana/dashboards/example-dashboard.json